/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const set_async_result_callback: (a: any) => void;
export const __wbg_terminal_free: (a: number, b: number) => void;
export const terminal_new: () => number;
export const terminal_init_terminal: (a: number) => any;
export const terminal_init_with_storage: (a: number) => any;
export const terminal_load_filesystem_data: (a: number, b: number, c: number) => any;
export const terminal_execute_command: (a: number, b: number, c: number) => any;
export const terminal_get_current_directory: (a: number) => [number, number];
export const terminal_list_files: (a: number, b: number, c: number) => any;
export const terminal_read_file: (a: number, b: number, c: number) => any;
export const terminal_write_file: (a: number, b: number, c: number, d: number, e: number) => any;
export const terminal_get_command_list: (a: number) => any;
export const terminal_get_environment_variables: (a: number) => any;
export const terminal_set_environment_variable: (a: number, b: number, c: number, d: number, e: number) => void;
export const terminal_is_nano_mode: (a: number) => number;
export const terminal_get_nano_filename: (a: number) => [number, number];
export const terminal_process_nano_input: (a: number, b: number, c: number) => any;
export const terminal_get_nano_editor_state: (a: number) => any;
export const get_assembly_template: (a: number, b: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_5: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb7ade31a031a667e: (a: number, b: number) => void;
export const closure150_externref_shim: (a: number, b: number, c: any) => void;
export const closure818_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
